### ISSUE TITLE
Rework Curriculum Submission Form

### ISSUE THREAD

**Issue by lukesanantonio** [lukesanantonio/firstbyte#72]
Existing Bugs:
- [x]  Fail with visible error when an existing curriculum with the same title already exists #51 
- [x]  Use separate line for each material for the curriculum #24 
- [ ]  Clearly display copyright information #14 
- [x]  Add custom form inputs for time duration #13
